### ISSUE TITLE
Detail for the Code

### ISSUE THREAD

**Issue by MingshanHe** [davideferrari95/onrobot_gipper#1]
Hello, I have some questions about the code.
First, you have used ros service exactly 'set io states' for changing the state of DO(16) and DO(17).
But as I have searched, the DO(8) and DO(9) are controlling the gripper close/open and force details.
So if you could express more for me? Because I have used both your code and changed DO(8) DO(9) in my code are not successfully run.

**Comment by davideferrari95** [comment]
Hi, this code was written to interface the gripper with the UR10e series manipulator, using the `ur_msgs::SetIO` service. 
This service overwrites the DO value on the robot teach pendant, so to test which DOs to use for your robot you can try to manually switch them on the TP.

Testing the gripper on our robot, the DO that govern the opening-closing and the force are 16 and 17. 
To modify them, simply change the numbers on lines 41 and 55 of the `src/onrobot_gripper.cpp` file.

**Comment by MingshanHe** [comment]
Thanks for your comment. Our hardware is UR5e series manipulator and the gripper is RG2 which is set up with the quick changer.    I can control the gripper with URCap and I have tried to change the DO from 0 to 17 in false and true. But it doesn't work. So would you like to share more details about the setup steps?  Now I have tested successfully with `Universal_Robot_ROS_Driver` and I used rosservice in it to change DO. And in teach pendant I have run the `External Control.urp` code.

**Comment by davideferrari95** [comment]
Our setup is very basic; we simply connected the gripper (there are two versions of the RG2 gripper, we have the [V1](https://www.google.com/url?sa=i&url=https%3A%2F%2Fonrobot.com%2Fsites%2Fdefault%2Ffiles%2Fdocuments%2FRG2_User%2520_Manual_enEN_V1.9.2.pdf&psig=AOvVaw3xyuY6p0unubsbli1dlejH&ust=1644483938647000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCMC_m5yi8vUCFQAAAAAdAAAAABAV)) to the end-effector of the robot through the standard plug. By doing so, even without starting the URCap or the ROS drivers, we can control the gripper through the two DO pins.

**Comment by MingshanHe** [comment]
Thank you very much. My gripper is V2, so there is a middle component between the end of UR5e and RG2 gripper which I have mentioned is Quick Changer. And I have changed DO pins with the teach pendant and I also can change it with `ur_msgs/SetIO` which can be seen with the teach pendant. Until Now I also have no answer on how to control the gripper with DO pins... If you have any answer, it is appreciated to contact me. Thanks for your answer again.

**Comment by davideferrari95** [comment]
Not having the new model we have never tested the control on this version, sorry. In theory, the gripper is recommended for universal robots so by contacting customer support they should be able to help you. Checking on the [website](https://www.roscomponents.com/en/grippers/293-rg2.html) it says that ROS nodes are not currently available and to contact support to integrate it into your robot. 

_"Recommended product for UR arms. For another arm model, please consult. The ROS drivers of this product aren't available yet, but it can be integrated with our robots very easily. Please consult us."_

I hope I was helpful. 

Greetings, 
Davide
